type: generation
output:
  output/red_team_attempts/gpt4o_zs.json
data:
  path: data/red_team_attempts.tsv
  target_name: red_team_attempt
  target_col: content
  time_col: split
  time_split: 1
  num_tests: 200
embeddings:
  path: data/red_team_attempts.npz
method:
  type: prompting
  init_args:
    model_name: gpt-4o
    prompt_type: red_zero-shot-prompting
    sampler_kwargs:
      k_min: 2
      k_max: 20
      dist_threshold: 0.1
    api_kwargs:
      request_url: https://api.openai.com/v1/chat/completions
      api_key: ${OPENAI_API_KEY}
      max_requests_per_minute: 500
      max_tokens_per_minute: 1000000
      token_encoding_name: cl100k_base
      max_attempts: 99
      logging_level: 10 # logging.DEBUG
