type: generation
output:
  output/red_team_attempts/vec2text_uw.json
data:
  path: data/red_team_attempts.tsv
  target_col: content
  time_col: split
  time_split: 1
  num_tests: 200
embeddings:
  path: data/red_team_attempts.npz
method:
  type: embedding
  init_args:
    weighted: False
    sampler_kwargs:
      k_min: 2
      k_max: 20
      dist_threshold: 0.1
    vec2text_kwargs:
      num_steps: 5
      sequence_beam_width: 0
