# Single GPU training t5-xxl using LoRA
model: google/flan-t5-xxl
tokenizer: google/flan-t5-xxl
data:
  path: data/massw_llm4explore.tsv
  target_col: key_idea
  time_col: year
  time_train: [1975, 2023]
  time_val: [2022, 2023]
  time_test: [2023, 2024]
  use_sampler: True
  sampler_kwargs:
    k_max: 3
  input_kwargs: null
  num_test: 200
embeddings:
  path: out/ada2_key_ideas.npz
training_args:
  learning_rate: 0.0002
  output_dir: /scratch/qmei_root/qmei/jimmyzxj/hf_checkpoints/t5-xxl-query-and-ref/lora_8/
  eval_strategy: steps
  per_device_train_batch_size: 2
  per_device_eval_batch_size: 2
  predict_with_generate: True
  logging_steps: 500
  save_steps: 10000
  eval_steps: 1000
  warmup_steps: 2000
  save_total_limit: 1
  num_train_epochs: 3
  report_to: wandb
  generation_max_length: 64
  run_name: t5-xxl-query-and-ref
  bf16: True
wandb_args:
  project: idea_generation
  group: t5-xxl
  name: t5-xxl-query-and-ref-lora8
lora_args:
  r: 8
  lora_alpha: 16
  target_modules: [q, v]
  lora_dropout: 0.05
  task_type: SEQ_2_SEQ_LM
metrics: [bleu, rouge, meteor, cosine]
