type: generation
output:
  out/finetune_t5_query_only.json
data:
  path: data/massw_llm4explore.tsv
  target_col: key_idea
  time_col: year
  time_split: 2023
  num_tests: 200
embeddings:
  path: out/ada2_key_ideas.npz
method:
  type: finetune
  init_args:
    checkpoint_dir: out/train/query_only/t5-query-only-3e-4/checkpoint-140000
    use_sampler: False
    sampler_kwargs: null
    input_kwargs: null
    batch_size: 8
