type: generation
output:
  out/gpt4_fs_rag_30.json
data:
  path: data/massw_llm4explore.tsv
  target_col: key_idea
  time_col: year
  time_split: 2023
  num_tests: 30
embeddings:
  path: data/ada2_key_ideas.npz
method:
  type: prompting
  init_args:
    model_name: gpt-4
    prompt_type: few-shot-rag-prompting
    rag_precompute_file: predata/pre_compute.pkl
    sampler_kwargs:
      k_min: 2
      k_max: 20
      dist_threshold: 0.1
    api_kwargs:
      request_url: https://embedding-api.openai.azure.com/openai/deployments/gpt-4/chat/completions?api-version=2023-12-01-preview
      api_key: ${AZURE_OPENAI_KEY}
      max_requests_per_minute: 10
      max_tokens_per_minute: 10000
      token_encoding_name: cl100k_base
      max_attempts: 1
      logging_level: 10 # logging.DEBUG
