type: generator
output:
  out/plagiarism_10.json
data:
  path: data/massw_llm4explore.tsv
  target_col: key_idea
  time_col: year
  time_split: 2023
  num_tests: 10
embeddings:
  path: out/ada2_key_ideas.npz
method:
  type: plagiarism
  init_args:
    sampler_kwargs:
      k: 5