type: generation
output:
  out/vec2text_uw_200.json
data:
  path: data/massw_llm4explore.tsv
  target_col: key_idea
  time_col: year
  time_split: 2023
  num_tests: 200
embeddings:
  path: data/ada2_key_ideas.npz
method:
  type: embedding
  weighted: False
  init_args:
    sampler_kwargs:
      k_min: 2
      k_max: 20
      dist_threshold: 0.1
    vec2text_kwargs:
      num_steps: 5
      sequence_beam_width: 0
