type: generation
output:
  out/plagiarism_200.json
data:
  path: data/persona.tsv
  target_col: persona
  time_col: split_id
  time_split: 1
  num_tests: 200
embeddings:
  path: data/persona.npz
method:
  type: plagiarism
  init_args:
    sampler_kwargs:
      k_min: 2
      k_max: 20
      dist_threshold: 0.1
