type: generation
output:
  output/persona/vec2text_ffn.json
data:
  path: data/persona.tsv
  target_col: persona
  time_col: split_id
  time_split: 1
  num_tests: 10
embeddings:
  path: data/persona.npz
method:
  type: embedding_ffn
  init_args:
    ffn_path: models/persona/ffn.th
    dim_out: 1024
    vec2text_kwargs:
      num_steps: 5
      sequence_beam_width: 0
