type: generation
output:
  output/prompt_log/gpt4o_fs_cot.json
data:
  path: data/prompt_log.tsv
  target_col: prompt
  time_col: split_id
  time_split: 1
  num_tests: 200
embeddings:
  path: data/prompt_log.npz
method:
  type: prompting
  init_args:
    model_name: gpt-4o
    prompt_type: prompt_few-shot-cot-prompting
    sampler_kwargs:
      k_min: 2
      k_max: 20
      dist_threshold: 0.1
    api_kwargs:
      request_url: https://api.openai.com/v1/chat/completions
      api_key: ${OPENAI_API_KEY}
      max_requests_per_minute: 500
      max_tokens_per_minute: 1000000
      token_encoding_name: cl100k_base
      max_attempts: 99
      logging_level: 10 # logging.DEBUG
