type: generation
output:
  output/prompt_log/plagiarism.json
data:
  path: data/prompt_log.tsv
  target_col: prompt
  time_col: split_id
  time_split: 1
  num_tests: 200
embeddings:
  path: data/prompt_log.npz
method:
  type: plagiarism
  init_args:
    sampler_kwargs:
      k_min: 2
      k_max: 20
      dist_threshold: 0.1
