type: generation
output:
  output/prompt_log/vec2text_ffn.json
data:
  path: data/prompt_log.tsv
  target_col: prompt
  time_col: split_id
  time_split: 1
  num_tests: 200
embeddings:
  path: data/prompt_log.npz
method:
  type: embedding_ffn
  init_args:
    ffn_path: models/prompt_log/ffn.th
    vec2text_kwargs:
      num_steps: 5
      sequence_beam_width: 0
