type: generation
output:
  output/persona/vec2text_uw_persona_test.json
data:
  path: data/persona.tsv
  target_col: persona
  time_col: split_id
  time_split: 1
  num_tests: 10
embeddings:
  path: data/persona.npz
method:
  type: embedding
  init_args:
    weighted: False
    sampler_kwargs:
      k_min: 2
      k_max: 20
      dist_threshold: 0.1
    vec2text_kwargs:
      num_steps: 5
      sequence_beam_width: 0
