type: mapping
data:
  path: data/massw.tsv
  target_col: context
method:
  type: plm_dr
  init_args:
    n_dims: 2
    save_path: data/context.npz
    plm_encoder: text-embedding-ada-002
    dr_algorithm: largevis
    plm_kwargs:
      request_url: https://api.openai.com/v1/embeddings
      api_key: ${OPENAI_API_KEY}
      max_requests_per_minute: 800
      max_tokens_per_minute: 180000
      token_encoding_name: cl100k_base
      max_attempts: 99
      logging_level: 10 # logging.DEBUG
    dr_kwargs:
      threads: 8
