type: generation
output:
  output/cs_research_context/plagiarism.json
data:
  path: data/massw.tsv
  target_col: context
  time_col: year
  time_split: 2023
  num_tests: 200
embeddings:
  path: data/context.npz
method:
  type: plagiarism
  init_args:
    sampler_kwargs:
      k_min: 2
      k_max: 20
      dist_threshold: 0.1
