type: generation
output:
  output/cs_research_context/vec2text_ffn.json
data:
  path: data/massw.tsv
  target_col: context
  time_col: year
  time_split: 2023
  num_tests: 200
embeddings:
  path: data/context.npz
method:
  type: embedding_ffn
  init_args:
    ffn_path: models/cs_research_context/ffn.th
    vec2text_kwargs:
      num_steps: 5
      sequence_beam_width: 0
