# Embedding interpolation (unweighted)
type: generation
output:
  output/cs_research_idea/vec2text_uw.json
data:
  path: data/massw.tsv
  target_col: context
  time_col: year
  time_split: 2023
  num_tests: 200
embeddings:
  path: data/context.npz
method:
  type: embedding
  init_args:
    weighted: False
    sampler_kwargs:
      k_min: 2
      k_max: 20
      dist_threshold: 0.1
    vec2text_kwargs:
      num_steps: 5
      sequence_beam_width: 0
