type: generation
output:
  output/vec2text_ffn.json
data:
  path: data/massw.tsv
  target_col: key_idea
  time_col: year
  time_split: 2023
  num_tests: 200
embeddings:
  path: data/key_idea.npz
method:
  type: embedding_ffn
  init_args:
    ffn_path: /home/shixuanl/llm4exploreV2/logs/ffn/model.pth
    vec2text_kwargs:
      num_steps: 5
      sequence_beam_width: 0
